### ISSUE TITLE
What location information to ask the user?  Zip code, latitude/longitude?  This is critical because it will drive all the geolocation-based matching functionality.

### ISSUE THREAD

**Issue by thebitguru** [CV19Assist/app#1]

**Comment by diogoribeiro** [comment]
latitude/longitude seems to be a good option and we have browser support for that
[https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API)

**Comment by thebitguru** [comment]
Thanks, @diogoribeiro. Any thoughts on how best to get those?  We can ask for zip code and have a zip code to long/lat mapping.  I haven't looked at the browser APIs yet, maybe we get that first and then fall back to the zip code mapping?

I also want us to be cautious of any privacy concerns.

**Comment by theBstar** [comment]
We can use browser geolocation api to get the long/lat and map to address with google map api. It requires permission from the user to access the location. We can even make the address auto complete with google map api, so people not opting for location auto detection can use the auto complete.

**Comment by thebitguru** [comment]
FYI, we ended up with a very simple approach this with one fast follower enhancement.  https://github.com/CV19Assist/app/issues/29
