### ISSUE TITLE
Community Map collaboration

### ISSUE THREAD

**Issue by dmitry-yudakov** [CV19Assist/app#109]
Hi guys,

Really great project you have here! I'd like to help.

We're a small community working on something called [Open Community Map](https://github.com/opencommunitymap/communitymap-ui).

It's a bit broader idea than yours but follow the same purpose - helping people in local areas to get organized better and collaborate more efficiently.

There are many projects recently (even too many maybe) trying to help with current situation and there's a great segmentation. The problem many of these projects need to overcome is lack of critical mass of users and publicity to get it working. Many teams also suffer from lack of developing team members.

We think it'd be great if such projects could work together in a common place creating an ecosystem of local and location-based services where everyone benefits from a bigger user base and gets a better chance to survive, grow and probably find partners. At the same time we want every project to keep its own individuality if they want and can afford to. The ultimate goal is to create a system where the end users have much greater understanding of what's going on in certain area and ability to participate in it and improve the world around them (it's a bit Hollywood, sorry, but it's true :) ).

It's a cool vision and hard to build, but it needs to start from somewhere. I see it as a common platform having API (or ability to fetch stuff for given area) and ability to be embedded into 3rd party website - currently as iframe, later as sdk/react library perhaps. It could show all data for visible area or filtered by the project or type. 

It's richer UI than just a marker on map, could show more on hover and click and for more functionality it could redirect to project's own website.

I'm sorry for the long post, but I can't explain it shorter.

Do you think we could help you with your project? If so, how exactly do you see it? And if no, pls tell why :)

It's a bit raw right now, it was born just few hackathons away but it's getting better and we honestly want to help - just need the right direction.

**Comment by prescottprue** [comment]
Thanks for reaching out! I will let @thebitguru speak to if/how this may fit into this project, but either way I think what you are saying about limiting segmentation is important. I also like the idea of similar projects working together where possible - I'll reach out on your repo to see where I might be able to help

**Comment by thebitguru** [comment]
Hello, @dmitry-yudakov!

Thank you for reaching out.  I think it's at least worth exploring further to see how we may be able to work together.

A few upfront questions:

* How long have you guys been live?
* Have you gotten any "traction" so far?
* Are you paired with any mutual aid or other companies to help with policies and other day-to-day execution?

Lastly, we have continually narrowed focus for CV19Assist to ensure that our resources could provide value and fill gaps that other organizations weren't filling; i.e. grocery delivery for at-health-risk population.  Now that, at least in the US, the states are reducing the restrictions, and commercial delivery companies like Instacart are catching up with the demand, the need for a project like CV19Assist has gone done significantly.  Is that the case for the focus of your efforts?  If so, how are you planning on responding to these changes?

**Comment by dmitry-yudakov** [comment]
Farhan, Scott, thank you for getting back to me!

The project was born at [The Global Hack](https://devpost.com/software/community-map-gzfnqv) 2 months ago and then "gravity-accelerated" on few more hackathons attracting some community members along the way. And it still goes on.

We started as a crisis-reaction project but our idea is not tightly focused and the project wasn't huge success. We noticed though lots of people out there with great expertise and years of research backing their ideas - better prepared than us and focused on solving certain problems. 

At these events very big number of projects are born but most are unable to assemble a team with all needed roles covered to grow into sustainable product working on its own. So we felt like we could adjust our idea and focus more on this problem - segmentation and lack of resources - and help some of projects to survive.

I agree with what you said - the first shock of the crisis has passed, the organizations are catching up and everything slowly moves to the  "new normal" - it seems to apply to the countries we have observations from - Bulgaria, Croatia, Italy. But I feel there's still need of an ecosystem where community-based and local ideas and services could get better conditions for grow.

Open source is pretty important for this as it increases the chances of cooperation rather than competition - and the pieces of projects falling apart will hopefully get attracted by other projects within the same ecosystem. 

The community control of development and content of this ecosystem should make it better fit to the real world and real needs - even after the current crisis is over. Or if the new wave happens again.

Our platform doesn't have users so far as we shifted our focus from end users to relevant 
projects. We have lots of contacts with them from past hackathons and pretty stable interest for solution like this in currently forming ones. Semi-working version of the solution was put together just few days ago and the tests of whether our concept fits real needs are in progress right now.

It's not a ready solution I'm offering as you can see - so far it's more of the placeholder that I'm trying to verify and adjust.

Our community is small yet but we managed to attract 5-6 experts with IT, logistics, hyperlocal marketing, EU programs and municipalities, legal and accounting. And more are joining. Relatively weak interest from fellow developers - most of the code I'm still writing myself. Few guys might be joining soon.

**Comment by thebitguru** [comment]
Thanks for your patience, @dmitry-yudakov.  I have been quite consumed by work lately so didn't get around to responding yet.  I feel it would be good to discuss on a call.  I see your LinkedIn profile on your github account so I will message you there to set up the call.

**Comment by thebitguru** [comment]
Continuing on email so closing this issue on github.
