### ISSUE TITLE
Research and document how multiple devs can work on a single Firebase project

### ISSUE THREAD

**Issue by thebitguru** [CV19Assist/app#12]

**Comment by MauricioSo** [comment]
I can  try this

**Comment by prescottprue** [comment]
There have been notes added to the README on the next branch about how to setup your dev environment including adding `.env.local`. This will allow devs to work in the same project as another dev if they choose, or use their own dev project.

Were we looking for anything else here?

**Comment by thebitguru** [comment]
Yup, that looks good enough for now. I will close this issue.
