### ISSUE TITLE
Create the firestore design

### ISSUE THREAD

**Issue by thebitguru** [CV19Assist/app#13]
Need to design the Firestore collection and attribute design.  Please document in this wiki entry https://github.com/CV19Assist/app/wiki/Datastore-Design

**Comment by thebitguru** [comment]
@thebstar any chance you can help with this?

**Comment by theBstar** [comment]
I have done the DB design earlier both in SQL and NoSQL. I will go through some resources (firestore) and update by March 18, 9 PM IST.

**Comment by thebitguru** [comment]
Hi, @theBstar, FYI, I am back online

**Comment by thebitguru** [comment]
Hi, @theBstar, FYI, I am back online.  Did you have any luck with this?

**Comment by theBstar** [comment]
Hi, I have done some research around and this is what I have come up with. I don't have write access to the wiki so I am updating here.


## Collections

### Users
    id,
    name: Text string,
    email: Text string,
    address: {
        line1: Text string,
        line2: Text string,
        city: Text string,
        state: Text string,
        zip: Integer,
        country: Text string,
        phone_number: Integer,
    },
    geolocation: {
        latitude: Number,
        longitude: Number,
        geohash: Text string, // used to do near by queries
    },

### Tasks
    id,
    title: Text string,
    description: Text string,
    type: Text string // can be one of shopping, emotional support, etc
    created_at: Date,
    created_by: Ref user_id,
    assigned_to: Ref user_id,
    status: Text string // can be one of open, in-progress and completed
    geolocation: {
        latitude: Number,
        longitude: Number,
        geohash: Text string, // used to do near by queries
    },
    meta: {
        started_at: Date,
        completed_at: Date,
    }

**Comment by anubhavgoel** [comment]
I can help with Needs collection
