### ISSUE TITLE
Create place holders text in UI

### ISSUE THREAD

**Issue by thebitguru** [CV19Assist/app#14]

**Comment by MauricioSo** [comment]
this one is available?

**Comment by thebitguru** [comment]
Hi, @MauricioSo, I will add more detail here in the next day or so.  As we discussed on Slack, I have shared another issue for you to help with.  Thanks, again!

**Comment by thebitguru** [comment]
This is not critical for now so I am closing the issue.  We will add it again if the need comes up in the future.
