### ISSUE TITLE
Clean up the dependencies and minimize the prod build

### ISSUE THREAD

**Issue by thebitguru** [CV19Assist/app#17]

**Comment by theBstar** [comment]
I can take this up.

**Comment by thebitguru** [comment]
That would be awesome.  We are not ready for this optimization yet.  I will assign this to you and ping when I feel like we are ready.  Thanks, again!

**Comment by prescottprue** [comment]
Not sure what optimizations were meant by this exactly, the changes for the new version [currently in progress on the `next` branch](https://github.com/CV19Assist/app/pull/58) are pretty lean as far as dependencies, so it may handle this

**Comment by thebitguru** [comment]
Thanks, @prescottprue!
