### ISSUE TITLE
Restructuring the project react specific

### ISSUE THREAD

**Issue by theBstar** [CV19Assist/app#18]
I am suggesting a restructuring of our project. This is only related to the **src** folder

Current:

- Src
  - components
    Holds the screens/pages
  - modules
    Holds the reducers & auth
 

Proposed:
- Src
  - components
    Holds reusable UI components
  - views
    Holds the screens/pages
  - store
   holds the redux store
  - modules
   holds other modules

I can do it and submit a pr by 10PM IST March 18.

**Comment by thebitguru** [comment]
Components in this case are basically any react components, i.e. views in your example.

FYI, I am using the ["ducks"](https://github.com/erikras/ducks-modular-redux) bundle approach to simplify development.

**Comment by theBstar** [comment]
Ok. I am going to close the issue.
