### ISSUE TITLE
Hook up Google Maps address lookup in the ClickableMap component

### ISSUE THREAD

**Issue by thebitguru** [CV19Assist/app#29]
We need to allow the user to enter an address and then use Google Maps API to lookup the geolocation.  Note that the [ClickableMap component](https://github.com/CV19Assist/app/blob/master/src/components/ClickableMap.js) is used on request help and the sign up screens. On the sign up screen, we also need to fill in the discrete address fields, if possible.

![image](https://user-images.githubusercontent.com/163550/77541978-7c10ed80-6e73-11ea-9a47-4f41dd97e831.png)

**Comment by thebitguru** [comment]
Anubhav might be interested in this

**Comment by anubhavgoel** [comment]
Please assign this issue to me

**Comment by thebitguru** [comment]
@anubhavgoel I was able to figure out the browser geolocation detection as coded in [ClickableMap](https://github.com/CV19Assist/app/blob/master/src/components/ClickableMap.js#L75).  I will update this issue with the remaining piece.

**Comment by thebitguru** [comment]
Hi, @anubhavgoel, any updates on this?  This is getting to the top of our list so, in the next few hours, I will likely start working on it too.

**Comment by thebitguru** [comment]
Implemented in https://github.com/CV19Assist/app/commit/823a01b7ab47db7719e52f684e9c301114e61ac8.

![image](https://user-images.githubusercontent.com/163550/80912163-b4240f80-8d00-11ea-85ba-d9e9e4cda9c7.png)
