### ISSUE TITLE
Hookup the frontend needs form

### ISSUE THREAD

**Issue by thebitguru** [CV19Assist/app#35]
API implementation https://github.com/CV19Assist/app/blob/master/functions/handlers/needs.js#L25

On successful posts, please redirect the user to "/need/posted".  Please create this new component (NeedPosted.js) as a copy of Volunteer.js component.

After the basic hookup, if you have time, please see https://github.com/CV19Assist/app/issues/34

**Comment by StephenTanksley** [comment]
I'll take this.
