### ISSUE TITLE
Decide on a way to differentiate between production and dev envs in firebase functions, and hookup the logic in the code

### ISSUE THREAD

**Issue by thebitguru** [CV19Assist/app#37]
As we get ready for production release, we need a way to differentiate between production and dev configs.  Maybe use NODE_ENV node var.

**Comment by MrSimsek** [comment]
Hi

**Comment by prescottprue** [comment]
I have done this for a number of other firebase projects and should be able to help out here

**Comment by thebitguru** [comment]
@prescottprue given your recent commits with the CI/CD pieces, are we all good here?

**Comment by prescottprue** [comment]
@thebitguru Yeah we should be good. There is no environment specific logic within the cloud functions in the next branch, so we should be good to close this
