### ISSUE TITLE
Create the blog section

### ISSUE THREAD

**Issue by thebitguru** [CV19Assist/app#46]
The source files is hosted in a github repo/github page and have the following format.

The index file will be `index.json` and have the following format.  It will return the blog entries in the needed order.  Let's not worry about pagination in the first iteration.
```
[{
	id: “random-id-here”,
	createdAt: “ISO-8601 timestamp”,
	title: “First Entry”,
	author: “Farhan Ahmad”,
	slug: “first-entry”,
	summary: “A quick description for the listing page.”
}, ...]
```

The individual entry files will are named `entry-{slug}.json` and will have the following format.
```
{
	id: “random-id-here”,
	createdAt: “ISO-8601 timestamp”,
	title: “First Entry”,
	author: “Farhan Ahmad”,
	slug: “first-entry”,
	summary: “A quick description for the listing page.”,
	html: “JSON-escaped HTML”
}
```

Examples:
https://cv19assist.github.io/blog/index.json
https://cv19assist.github.io/blog/entry-first-entry.json

# Site Functionality

The above should result in the following routes on the front end.

`/blog` — Listing page
`/blog/<slug>` — Specific blog entry

Feel free to see the [source blog repo](https://github.com/CV19Assist/blog) if you are curious about the generation process.

**Comment by MauricioSo** [comment]
I can work on this

**Comment by thebitguru** [comment]
Thanks, @MauricioSo!  Please feel free to ask any questions here or on slack.
