### ISSUE TITLE
Implement simple notifications

### ISSUE THREAD

**Issue by thebitguru** [CV19Assist/app#49]
Please see details in the design document that I shared.  I will update this issue with the details in a bit.

**Comment by MrSimsek** [comment]
Hey

**Comment by prescottprue** [comment]
Have a used FCM a bunch before, so started working on this after chatting with @thebitguru. The work is currently in [the next branch PR for the version update](https://github.com/CV19Assist/app/pull/58)

**Comment by prescottprue** [comment]
@thebitguru Did you want to close this ticket since we got the simple setup in place for new requests (email + FCM), and the daily (email)? Or did you want to implement some more functionality first?

**Comment by thebitguru** [comment]
Yes, I am closing this issue and will create another one for Milestone 5 with a few more changes to get it ready for general rollout.
