### ISSUE TITLE
Convert the contact page to an actual form

### ISSUE THREAD

**Issue by thebitguru** [CV19Assist/app#60]
We need to convert the contact page to an actual React form.  It should have the following fields and add to the `contacts` collections in Firebase.

1. Name
2. Email
3. Phone - optional
4. Organization - optional
5. Message 

Furthermore, it should also email the administrators on submission.  The project uses the [Trigger Email extension](https://firebase.google.com/products/extensions/firestore-send-email) so emailing requires adding a new document to the `mail` collection.

@prescottprue, can you please update this with the collection where you were suggesting saving the admin emails?

Please note that all new development is now being done on the `next` branch which will be going live in the coming days.  Please branch off of it if working on this task.

**Comment by prescottprue** [comment]
Going to close since [this PR for doing this](https://github.com/CV19Assist/app/pull/62) was merged into `next`
