### ISSUE TITLE
Request notification permission only when needed

### ISSUE THREAD

**Issue by thebitguru** [CV19Assist/app#63]
Thanks for working on the notification, @prescottprue.  I noticed that the browser prompts even when the user is not logged in, e.g. when a new anonymous person visits the website.  Can we request the notification permission only for logged in users?

**Comment by thebitguru** [comment]
Also, the new site doesn't work on Safari currently likely because of FCM incompatibility.  I am on macOS 10.15.4/Safari 13.1.

```
FirebaseError: Messaging: This browser doesn't support the API's required to use the firebase SDK. (messaging/unsupported-browser).
```

The screen goes blank.  Same behavior on iOS.  [This issue](https://github.com/firebase/firebase-js-sdk/issues/1260) is likely related.

**Comment by prescottprue** [comment]
The fix for Safari has been released in next - confirmed in Safari and on IOS.

[Here is a PR](https://github.com/CV19Assist/app/pull/64) for only enabling messaging if the user is logged in
