### ISSUE TITLE
The request page shows an error when creating a request for a non-logged in user

### ISSUE THREAD

**Issue by thebitguru** [CV19Assist/app#85]
**Describe the bug**

1. Create a new request without logging in.
2. The console sometimes logs an error about [this line](https://github.com/CV19Assist/app/blob/cf28f724e002dc497fbf70dedc4479bc3697dca5/src/routes/NewRequest/components/NewRequestPage/NewRequestPage.js#L328).

**Comment by tescher** [comment]
I can take it

**Comment by prescottprue** [comment]
Nice! Welcome @tescher! Feel free to reach out if you have any questions about how things are currently working

**Comment by thebitguru** [comment]
I found the case that was causing this error.  When you sign up using email address, there is no `displayName` set on the `user` document which a lot of our logic assumes is required, and then breaks.
