### ISSUE TITLE
Fix firestore rules

### ISSUE THREAD

**Issue by thebitguru** [CV19Assist/app#89]
Now that we pushed out the `next` branch live, we need to make the firestore rules more secure.

**Comment by tescher** [comment]
Assign it to me

**Comment by prescottprue** [comment]
@tescher I am pretty confident with writing security rules, so let me know if I can be of any help!

**Comment by tescher** [comment]
@prescottprue Thanks! I created my first rule test based on the Quickstart. Can you take a look at my twe-small-fixes branch and see if I'm on the right track? 

tescher/app
