### ISSUE TITLE
Create tests for the request workflow

### ISSUE THREAD

**Issue by thebitguru** [CV19Assist/app#90]
We need to add cypress tests for the following:

1. Request acceptance
1. Request release
1. Request completion
1. Add admin comment on a request
1. Add private comment on a request

**Comment by tescher** [comment]
I can try this one unless there are more important things

**Comment by thebitguru** [comment]
Sure!  This is part of the current milestone.  It will also give you more exposure to the workflow.

One thing that I am not fully clear on is fixtures for testing. It would be good to talk through those once you have had a chance to do some research on testing.

**Comment by thebitguru** [comment]
Actually, I take that back. From the commits it looks like Prescott is already working on them.  @prescottprue ?

**Comment by prescottprue** [comment]
That is correct - I have the ones listed and made [this PR](https://github.com/CV19Assist/app/pull/99).

@tescher I also made the changes for loading API key from the .env file instead of needing to set it in `cypress.env.json`
